"""Shared helpers for DOCX tests: in-code document builders + raw-zip part injection.

python-docx cannot *create* ``docProps/custom.xml``, ``word/people.xml`` or
Manager/Company in ``app.xml`` — it only preserves them on round-trip. Tests
therefore splice minimal but valid parts into a package python-docx wrote,
reusing the generic zip helpers from :mod:`tests.file_analysis.xlsx_helpers`.
Everything is in-code — the repo keeps no binary fixtures.
"""

from __future__ import annotations

import html
import io
import re

from docx.document import Document as DocumentObject

from tests.file_analysis.xlsx_helpers import (
    _XML_HEAD,
    add_content_types,
    read_part,
    rewrite_zip,
)

_REL = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
_NS_PKG = "http://schemas.openxmlformats.org/package/2006/relationships"
_EXT_NS = "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"
_VT_NS = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"
_CUSTOM_NS = "http://schemas.openxmlformats.org/officeDocument/2006/custom-properties"
_W15_NS = "http://schemas.microsoft.com/office/word/2012/wordml"

DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

# A JPEG SOI marker followed by junk — enough to be "a thumbnail" for zip-level tests.
FAKE_JPEG = b"\xff\xd8\xff\xe0" + b"NOIRDOC-FAKE-THUMBNAIL"


def document_bytes(doc: DocumentObject) -> bytes:
    """Serialize a python-docx document to bytes."""
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _append_before(xml: bytes, closing: bytes, insert: str) -> bytes:
    assert closing in xml, closing
    return xml.replace(closing, insert.encode() + closing, 1)


def strip_template_noise(data: bytes) -> bytes:
    """Remove the default-template parts that would otherwise dominate counts.

    python-docx's bundled template ships a ``docProps/thumbnail.jpeg``, a
    ``customXml/`` bibliography island and ``dc:creator`` "python-docx" —
    all of which the scrubber (rightly) reports. Tests that exercise other
    surfaces start from a package without them.
    """
    rels = read_part(data, "_rels/.rels")
    rels = re.sub(rb"<Relationship [^>]*thumbnail[^>]*/>", b"", rels)
    doc_rels = read_part(data, "word/_rels/document.xml.rels")
    doc_rels = re.sub(rb"<Relationship [^>]*customXml[^>]*/>", b"", doc_rels)
    core = read_part(data, "docProps/core.xml")
    core = core.replace(b"<dc:creator>python-docx</dc:creator>", b"<dc:creator/>")
    core = core.replace(
        b"<dc:description>generated by python-docx</dc:description>", b"<dc:description/>"
    )
    return rewrite_zip(
        data,
        {
            "_rels/.rels": rels,
            "word/_rels/document.xml.rels": doc_rels,
            "docProps/core.xml": core,
            "docProps/thumbnail.jpeg": None,
            "customXml/item1.xml": None,
            "customXml/_rels/item1.xml.rels": None,
            "customXml/itemProps1.xml": None,
        },
    )


def clean_document_bytes(doc: DocumentObject) -> bytes:
    """Serialize *doc* without the default-template noise parts."""
    return strip_template_noise(document_bytes(doc))


def inject_app_props(
    data: bytes,
    *,
    manager: str = "",
    company: str = "",
    hyperlink_base: str = "",
    titles_of_parts: list[str] | None = None,
) -> bytes:
    """Replace ``docProps/app.xml`` with one carrying the given fields."""
    titles = titles_of_parts or []
    lpstrs = "".join(f"<vt:lpstr>{html.escape(t, quote=False)}</vt:lpstr>" for t in titles)
    app = (
        f'{_XML_HEAD}<Properties xmlns="{_EXT_NS}" xmlns:vt="{_VT_NS}">'
        f"<Application>Microsoft Word</Application>"
        f"<Manager>{html.escape(manager, quote=False)}</Manager>"
        f"<Company>{html.escape(company, quote=False)}</Company>"
        f"<HyperlinkBase>{html.escape(hyperlink_base, quote=False)}</HyperlinkBase>"
        f'<TitlesOfParts><vt:vector size="{len(titles)}" baseType="lpstr">{lpstrs}</vt:vector>'
        f"</TitlesOfParts></Properties>"
    )
    return rewrite_zip(data, {"docProps/app.xml": app.encode()})


def inject_custom_props(data: bytes, props: dict[str, str | int]) -> bytes:
    """Add a ``docProps/custom.xml`` part (str -> lpwstr, int -> i4)."""
    entries = []
    for pid, (name, value) in enumerate(props.items(), start=2):
        if isinstance(value, int):
            body = f"<vt:i4>{value}</vt:i4>"
        else:
            body = f"<vt:lpwstr>{html.escape(value, quote=False)}</vt:lpwstr>"
        entries.append(
            f'<property fmtid="{{D5CDD505-2E9C-101B-9397-08002B2CF9AE}}" pid="{pid}" '
            f'name="{html.escape(name, quote=True)}">{body}</property>'
        )
    custom = (
        f'{_XML_HEAD}<Properties xmlns="{_CUSTOM_NS}" xmlns:vt="{_VT_NS}">'
        + "".join(entries)
        + "</Properties>"
    )
    rels = _append_before(
        read_part(data, "_rels/.rels"),
        b"</Relationships>",
        f'<Relationship Id="rIdCustomProps" Type="{_REL}/custom-properties" '
        'Target="docProps/custom.xml"/>',
    )
    out = rewrite_zip(data, {"docProps/custom.xml": custom.encode(), "_rels/.rels": rels})
    return add_content_types(
        out,
        [
            (
                "/docProps/custom.xml",
                "application/vnd.openxmlformats-officedocument.custom-properties+xml",
            )
        ],
    )


def inject_people(data: bytes, *, author: str, user_id: str, provider_id: str = "AD") -> bytes:
    """Add a ``word/people.xml`` part (modern comment identities)."""
    people = (
        f'{_XML_HEAD}<w15:people xmlns:w15="{_W15_NS}">'
        f'<w15:person w15:author="{html.escape(author, quote=True)}">'
        f'<w15:presenceInfo w15:providerId="{html.escape(provider_id, quote=True)}" '
        f'w15:userId="{html.escape(user_id, quote=True)}"/></w15:person></w15:people>'
    )
    doc_rels = _append_before(
        read_part(data, "word/_rels/document.xml.rels"),
        b"</Relationships>",
        '<Relationship Id="rIdPeople" '
        'Type="http://schemas.microsoft.com/office/2011/relationships/people" '
        'Target="people.xml"/>',
    )
    out = rewrite_zip(
        data, {"word/people.xml": people.encode(), "word/_rels/document.xml.rels": doc_rels}
    )
    return add_content_types(
        out,
        [
            (
                "/word/people.xml",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.people+xml",
            )
        ],
    )


def inject_thumbnail(data: bytes, content: bytes = FAKE_JPEG) -> bytes:
    """Add (or replace) ``docProps/thumbnail.jpeg`` plus its package relationship."""
    rels = read_part(data, "_rels/.rels")
    if b"thumbnail" not in rels:
        rels = _append_before(
            rels,
            b"</Relationships>",
            '<Relationship Id="rIdThumb" '
            f'Type="{_NS_PKG}/metadata/thumbnail" Target="docProps/thumbnail.jpeg"/>',
        )
    return rewrite_zip(data, {"docProps/thumbnail.jpeg": content, "_rels/.rels": rels})


def inject_custom_xml(data: bytes, *, xml_text: str) -> bytes:
    """Add a ``customXml/`` data island referenced from the main document."""
    item = f"{_XML_HEAD}{xml_text}"
    item_props = (
        f'{_XML_HEAD}<ds:datastoreItem ds:itemID="{{11111111-2222-3333-4444-555555555555}}" '
        'xmlns:ds="http://schemas.openxmlformats.org/officeDocument/2006/customXml">'
        "<ds:schemaRefs/></ds:datastoreItem>"
    )
    item_rels = (
        f'{_XML_HEAD}<Relationships xmlns="{_NS_PKG}"><Relationship Id="rId1" '
        f'Type="{_REL}/customXmlProps" Target="itemProps9.xml"/></Relationships>'
    )
    doc_rels = _append_before(
        read_part(data, "word/_rels/document.xml.rels"),
        b"</Relationships>",
        f'<Relationship Id="rIdCX9" Type="{_REL}/customXml" Target="../customXml/item9.xml"/>',
    )
    out = rewrite_zip(
        data,
        {
            "customXml/item9.xml": item.encode(),
            "customXml/_rels/item9.xml.rels": item_rels.encode(),
            "customXml/itemProps9.xml": item_props.encode(),
            "word/_rels/document.xml.rels": doc_rels,
        },
    )
    return add_content_types(
        out,
        [
            (
                "/customXml/itemProps9.xml",
                "application/vnd.openxmlformats-officedocument.customXmlProperties+xml",
            )
        ],
    )
